name: SSH

description: Access remote host through ssh

inputs:
  ssh_key:
    description: ssh private key
    required: true

  ssh_user:
    description: remote host username
    required: true

  ssh_host:
    descrition: remote host address
    required: true

  command:
    description: command to be executed in the remote host
    required: true

outputs:
  output:
    description: output from the given command
    value: ${{ steps.run_command.outputs.response }}

runs:
  using: composite
  steps:
    - name: create ssh key file
      shell: bash
      run: |
        SSH_ACTION_KEY_NAME="KEY_$RANDOM"
        echo "SSH_ACTION_KEY_NAME=$SSH_ACTION_KEY_NAME" >> $GITHUB_ENV

        mkdir -p ~/.ssh
        echo '${{ inputs.ssh_key }}' > ~/.ssh/$SSH_ACTION_KEY_NAME
        sudo chmod 400 ~/.ssh/$SSH_ACTION_KEY_NAME

    - name: run the command
      id: run_command
      shell: bash
      run: |
        ACTION_RESPONSE=$( \
          ssh ${{ inputs.ssh_user }}@${{ inputs.ssh_host }} \
          -o PubKeyAuthentication=yes -o RequestTTY=no -o StrictHostKeyChecking=no \
          -i ~/.ssh/$SSH_ACTION_KEY_NAME \
          '${{ inputs.command }}' \
        )

        # replace Github unhandled characters (::set-output don't support multiline)
        ACTION_RESPONSE="${ACTION_RESPONSE//'%'/'%25'}"
        ACTION_RESPONSE="${ACTION_RESPONSE//$'\n'/'%0A'}"
        ACTION_RESPONSE="${ACTION_RESPONSE//$'\r'/'%0D'}"

        echo "::set-output name=response::$ACTION_RESPONSE"

    - name: remove ssh key
      if: always()
      shell: bash
      run: rm ~/.ssh/$SSH_ACTION_KEY_NAME
