name: SSH

description: Access remote host through ssh

inputs:
  ssh_key:
    description: ssh private key
    required: true

  ssh_user:
    description: remote host username
    required: true

  ssh_host:
    descrition: remote host address
    required: true

  command:
    description: command to be executed in the remote host
    required: true

runs:
  using: composite
  steps:
    - name: create ssh config file
      shell: bash
      run: |
        SSH_ACTION_KEY_NAME="KEY_$RANDOM"
        echo "SSH_ACTION_KEY_NAME=$SSH_ACTION_KEY_NAME" >> $GITHUB_ENV

        SSH_ACTION_SERVER_NAME="SERVER_$RANDOM"
        echo "SSH_ACTION_SERVER_NAME=$SSH_ACTION_SERVER_NAME" >> $GITHUB_ENV

        mkdir -p ~/.ssh
        echo '${{ inputs.ssh_key }}' > ~/.ssh/$SSH_ACTION_KEY_NAME
        sudo chmod 400 ~/.ssh/$SSH_ACTION_KEY_NAME

        cat >> ~/.ssh/config <<FINISH
        Host $SSH_ACTION_SERVER_NAME
          Hostname ${{ inputs.ssh_host }}
          User ${{ inputs.ssh_user }}
          PubKeyAuthentication yes
          RequestTTY no
          StrictHostKeyChecking no
          IdentityFile ~/.ssh/$SSH_ACTION_KEY_NAME
        FINISH

    - name: run the command
      shell: bash
      run: ssh $SSH_ACTION_SERVER_NAME '${{ inputs.command }}'

    - name: remove ssh key
      if: always()
      shell: bash
      run: rm ~/.ssh/$SSH_ACTION_KEY_NAME
